---
title: "Raw_data"
format: html
editor: visual
---

```{r}
#| label: packages
#| echo: FALSE
#here::here()
invisible(pacman::p_load(dplyr, tidyverse, here, stringi))

#This code chunk is dedicated to variables containing the path to the folder related to the project. 
figs_dir <- file.path("Results", "Figures")
tabs_dir <- file.path("Results", "Tables")
working_dir <- file.path("Data", "Working_data", "Processed_data")
```

### Rawdata
The output of this function is saved as e.g. **R154_R1.csv** for each DNA plate and treatment (R1, R2, R3, R4). They can be found in the working_dir. 
```{r}
#| label: rawdata
#| eval: False
#| echo: FALSE

#make list with path to all files
Data_files <- list.files(path = "Data/Working_data", pattern = "*.csv", full.names = T)
Mix1_locate <- grep("mix1", Data_files)
Mix1 <- Data_files[Mix1_locate]

Data_list = list()
#Broken well
remove_row <- c("E03_Empty")

#for loop which reads the csv files, removes the broken well and collects the dataframes in one list for mix 1
for(i in Data_files[Mix1_locate]) {
  x <- read.csv(i, sep = ";")
  x <- subset(x, ID != remove_row)
  Data_list[[i]] <- x
  #The following line tidies up the names of the files
   names(Data_list) <- gsub("Data/Working_data/AP_AFS_|AFS|_\\d{2}|_AlleleReport.csv", "", names(Data_list))
   names(Data_list) <- gsub("Data/Working_data/ALB__|AFS_|_\\d{2}|_AlleleReport.csv", "", names(Data_list))
}

#for loop which reads the csv files, removes the broken well and the columns 'rack_location' and 'id' and collects the dataframes in one list for other mixes than mix one.
for(i in Data_files[-Mix1_locate]) {
  x <- read.csv(i, sep = ";")
  x <- subset(x, ID != remove_row, select = -c(Rack_location, ID))
  Data_list[[i]] <- x
  #The following line tidies up the names of the files
  names(Data_list) <- gsub("Data/Working_data/AP_AFS_|AFS|_\\d{2}|_AlleleReport.csv", "", names(Data_list))
  names(Data_list) <- gsub("Data/Working_data/ALB__|AFS_|_\\d{2}|_AlleleReport.csv", "", names(Data_list))
  }

#The loci ZcwCO1 in mix 2 and ZcwCO3 in mix five is the same locus. Therefore, they need to be merged and the second version removed

ZcwCO1_loci <- function(DF) {
  #ZcwCO1
  change_a <- which(DF$mix2.ZcwCO1_a != DF$mix5.ZcwC03_a | is.na(DF$mix2.ZcwCO1_a) == T)
  change_b <- which(DF$mix2.ZcwCO1_b != DF$mix5.ZcwC03_b | is.na(DF$mix2.ZcwCO1_b) == T)
  DF$mix2.ZcwCO1_a[change_a] <- DF$mix5.ZcwC03_a[change_a]
  DF$mix2.ZcwCO1_b[change_b] <- DF$mix5.ZcwC03_b[change_b]
  DF <- subset(DF, select = -c(mix5.ZcwC03_a, mix5.ZcwC03_b))
}

Mangs_loci <- function(DF) {
  #Mangs
  Mangs44_a <- which(DF$mix5.Mang44_a != DF$Mangs.Mang44_a | is.na(DF$mix5.Mang44_a) == T)
  Mangs44_b <- which(DF$mix5.Mang44_b != DF$Mangs.Mang44_b | is.na(DF$mix5.Mang44_b) == T)
  Mangs36_a <- which(DF$mix5.Mang36_a != DF$Mangs.Mang36_a | is.na(DF$mix5.Mang36_a) == T)
  Mangs36_b <- which(DF$mix5.Mang36_b != DF$Mangs.Mang36_b | is.na(DF$mix5.Mang36_b) == T)
  DF$mix5.Mang44_a[Mangs44_a] <- DF$Mangs.Mang44_a[Mangs44_a]
  DF$mix5.Mang44_b[Mangs44_b] <- DF$Mangs.Mang44_b[Mangs44_b]
  DF$mix5.Mang36_a[Mangs36_a] <- DF$Mangs.Mang36_a[Mangs36_a]
  DF$mix5.Mang36_b[Mangs36_b] <- DF$Mangs.Mang36_b[Mangs36_b]
  DF <- subset(DF, select = -c(Mangs.Mang44_a, Mangs.Mang44_b, Mangs.Mang36_a, Mangs.Mang36_b))
}

Mang44_loci <- function(DF) {
  #Mang44
  Mangs44_a <- which(DF$mix5.Mang44_a != DF$Mang.Mang44_a | is.na(DF$mix5.Mang44_a) == T)
  Mangs44_b <- which(DF$mix5.Mang44_b != DF$Mang.Mang44_b | is.na(DF$mix5.Mang44_b) == T)
  DF$mix5.Mang44_a[Mangs44_a] <- DF$Mang.Mang44_a[Mangs44_a]
  DF$mix5.Mang44_b[Mangs44_b] <- DF$Mang.Mang44_b[Mangs44_b]
  DF <- subset(DF, select = -c(Mang.Mang44_a, Mang.Mang44_b))
}

OrrFCB2_loci <- function(DF) {
  #Mang44
  OrrFCB2_a <- which(DF$mix2.OrrFCB2_a != DF$OrrFCB2.OrrFCB2_a | is.na(DF$mix2.OrrFCB2_a) == T)
  OrrFCB2_b <- which(DF$mix2.OrrFCB2_b != DF$OrrFCB2.OrrFCB2_b | is.na(DF$mix2.OrrFCB2_b) == T)
  DF$mix2.OrrFCB2_a[OrrFCB2_a] <- DF$OrrFCB2.OrrFCB2_a[OrrFCB2_a]
  DF$mix2.OrrFCB2_b[OrrFCB2_b] <- DF$OrrFCB2.OrrFCB2_b[OrrFCB2_b]
  DF <- subset(DF, select = -c(OrrFCB2.OrrFCB2_a, OrrFCB2.OrrFCB2_b))
}

PvcEMangs <- function(DF) {
  #Mang44
  Mangs44_a <- which(DF$mix5.Mang44_a != DF$PvcEMangs.Mang44_a | is.na(DF$mix5.Mang44_a) == T)
  Mangs44_b <- which(DF$mix5.Mang44_b != DF$PvcEMangs.Mang44_b | is.na(DF$mix5.Mang44_b) == T)
  DF$mix5.Mang44_a[Mangs44_a] <- DF$PvcEMangs.Mang44_a[Mangs44_a]
  DF$mix5.Mang44_b[Mangs44_b] <- DF$PvcEMangs.Mang44_b[Mangs44_b]
  #PvcE
  PvcE_a <- which(DF$mix5.PvcE_a != DF$PvcEMangs.PvcE_a | is.na(DF$mix5.PvcE_a) == T)
  PvcE_b <- which(DF$mix5.PvcE_b != DF$PvcEMangs.PvcE_b | is.na(DF$mix5.PvcE_b) == T)
  DF$mix5.PvcE_a[PvcE_a] <- DF$PvcEMangs.PvcE_a[PvcE_a]
  DF$mix5.PvcE_b[PvcE_b] <- DF$PvcEMangs.PvcE_b[PvcE_b]
  DF <- subset(DF, select = -c(PvcEMangs.Mang44_a, PvcEMangs.Mang44_b, PvcEMangs.PvcE_a, PvcEMangs.PvcE_b))
}

PvcEMangs4436 <- function(DF) {
   #Mangs
  Mangs44_a <- which(DF$mix5.Mang44_a != DF$PvcEMangs4436.Mang44_a | is.na(DF$mix5.Mang44_a) == T)
  Mangs44_b <- which(DF$mix5.Mang44_b != DF$PvcEMangs4436.Mang44_b | is.na(DF$mix5.Mang44_b) == T)
  Mangs36_a <- which(DF$mix5.Mang36_a != DF$PvcEMangs4436.Mang36_a | is.na(DF$mix5.Mang36_a) == T)
  Mangs36_b <- which(DF$mix5.Mang36_b != DF$PvcEMangs4436.Mang36_b | is.na(DF$mix5.Mang36_b) == T)
  DF$mix5.Mang44_a[Mangs44_a] <- DF$PvcEMangs4436.Mang44_a[Mangs44_a]
  DF$mix5.Mang44_b[Mangs44_b] <- DF$PvcEMangs4436.Mang44_b[Mangs44_b]
  DF$mix5.Mang36_a[Mangs36_a] <- DF$PvcEMangs4436.Mang36_a[Mangs36_a]
  DF$mix5.Mang36_b[Mangs36_b] <- DF$PvcEMangs4436.Mang36_b[Mangs36_b]
  #PvcE
  PvcE_a <- which(DF$mix5.PvcE_a != DF$PvcEMangs4436.PvcE_a | is.na(DF$mix5.PvcE_a) == T)
  PvcE_b <- which(DF$mix5.PvcE_b != DF$PvcEMangs4436.PvcE_b | is.na(DF$mix5.PvcE_b) == T)
  DF$mix5.PvcE_a[PvcE_a] <- DF$PvcEMangs4436.PvcE_a[PvcE_a]
  DF$mix5.PvcE_b[PvcE_b] <- DF$PvcEMangs4436.PvcE_b[PvcE_b]
  DF <- subset(DF, select = -c(PvcEMangs4436.Mang36_a, PvcEMangs4436.Mang36_b, PvcEMangs4436.Mang44_a, PvcEMangs4436.Mang44_b, PvcEMangs4436.PvcE_a, PvcEMangs4436.PvcE_b))
}

Mix1 <- function(DF) {
  #In the last rounds, the first 5 samples were compromised due to low DNA
  #Therefore, these samples are more likely to be correct then from the gapfilling plates
  First_5 <- DF[1:5,]

  Pv9_a <- which(DF$mix1.Pv9_a != DF$mix1gap.Pv9_a | is.na(DF$mix1.Pv9_a) == T)
  Pv9_b <- which(DF$mix1.Pv9_b != DF$mix1gap.Pv9_b | is.na(DF$mix1.Pv9_b) == T)
  Hg.6.3_a <- which(DF$mix1.Hg.6.3_a != DF$mix1gap.Hg.6.3_a | is.na(DF$mix1.Hg.6.3_a) == T)
  Hg.6.3_b <- which(DF$mix1.Hg.6.3_b != DF$mix1gap.Hg.6.3_b | is.na(DF$mix1.Hg.6.3_b) == T)
  Hg.8.10_a <- which(DF$mix1.Hg.8.10_a != DF$mix1gap.Hg.8.10_a | is.na(DF$mix1.Hg.8.10_a) == T)
  Hg.8.10_b <- which(DF$mix1.Hg.8.10_b != DF$mix1gap.Hg.8.10_b | is.na(DF$mix1.Hg.8.10_b) == T)
  Hg.1.3_a <- which(DF$mix1.Hg.1.3_a != DF$mix1gap.Hg.1.3_a | is.na(DF$mix1.Hg.1.3_a) == T)
  Hg.1.3_b <- which(DF$mix1.Hg.1.3_b != DF$mix1gap.Hg.1.3_b | is.na(DF$mix1.Hg.1.3_b) == T)
  M11a_a <- which(DF$mix1.M11a_a != DF$mix1gap.M11a_a | is.na(DF$mix1.M11a_a) == T)
  M11a_b <- which(DF$mix1.M11a_b != DF$mix1gap.M11a_b | is.na(DF$mix1.M11a_b) == T)
  PvcA_a <- which(DF$mix1.PvcA_a != DF$mix1gap.PvcA_a | is.na(DF$mix1.PvcA_a) == T)
  PvcA_b <- which(DF$mix1.PvcA_b != DF$mix1gap.PvcA_b | is.na(DF$mix1.PvcA_b) == T)
  Zcwb07_a <- which(DF$mix1.Zcwb07_a != DF$mix1gap.Zcwb07_a | is.na(DF$mix1.Zcwb07_a) == T)
  Zcwb07_b <- which(DF$mix1.Zcwb07_b != DF$mix1gap.Zcwb07_b | is.na(DF$mix1.Zcwb07_b) == T)
  Agaz.2_a <- which(DF$mix1.Agaz.2_a != DF$mix1gap.Agaz.2_a | is.na(DF$mix1.Agaz.2_a) == T)
  Agaz.2_b <- which(DF$mix1.Agaz.2_b != DF$mix1gap.Agaz.2_b | is.na(DF$mix1.Agaz.2_b) == T)

  DF$mix1.Pv9_a[Pv9_a] <- DF$mix1gap.Pv9_a[Pv9_a]
  DF$mix1.Pv9_b[Pv9_b] <- DF$mix1gap.Pv9_b[Pv9_b]
  DF$mix1.Hg.6.3_a[Hg.6.3_a] <- DF$mix1gap.Hg.6.3_a[Hg.6.3_a]
  DF$mix1.Hg.6.3_b[Hg.6.3_b] <- DF$mix1gap.Hg.6.3_b[Hg.6.3_b]
  DF$mix1.Hg.8.10_a[Hg.8.10_a] <- DF$mix1gap.Hg.8.10_a[Hg.8.10_a]
  DF$mix1.Hg.8.10_b[Hg.8.10_b] <- DF$mix1gap.Hg.8.10_b[Hg.8.10_b]
  DF$mix1.Hg.1.3_a[Hg.1.3_a] <- DF$mix1gap.Hg.1.3_a[Hg.1.3_a]
  DF$mix1.Hg.1.3_b[Hg.1.3_b] <- DF$mix1gap.Hg.1.3_b[Hg.1.3_b]
  DF$mix1.M11a_a[M11a_a] <- DF$mix1gap.M11a_a[M11a_a]
  DF$mix1.M11a_b[M11a_b] <- DF$mix1gap.M11a_b[M11a_b]
  DF$mix1.PvcA_a[PvcA_a] <- DF$mix1gap.PvcA_a[PvcA_a]
  DF$mix1.PvcA_b[PvcA_b] <- DF$mix1gap.PvcA_b[PvcA_b]
  DF$mix1.Zcwb07_a[Zcwb07_a] <- DF$mix1gap.Zcwb07_a[Zcwb07_a]
  DF$mix1.Zcwb07_b[Zcwb07_b] <- DF$mix1gap.Zcwb07_b[Zcwb07_b]
  DF$mix1.Agaz.2_a[Agaz.2_a] <- DF$mix1gap.Agaz.2_a[Agaz.2_a]
  DF$mix1.Agaz.2_b[Agaz.2_b] <- DF$mix1gap.Agaz.2_b[Agaz.2_b]

  DF[1:5,] <- First_5

  DF <- subset(DF, select = -c(mix1gap.Rack_location, mix1gap.ID, mix1gap.Pv9_a, mix1gap.Pv9_b, mix1gap.Hg.6.3_a, mix1gap.Hg.6.3_b, mix1gap.Hg.8.10_a, mix1gap.Hg.8.10_b, mix1gap.Hg.1.3_a, mix1gap.Hg.1.3_b, mix1gap.M11a_a, mix1gap.M11a_b, mix1gap.PvcA_a, mix1gap.PvcA_b, mix1gap.Zcwb07_a, mix1gap.Zcwb07_b, mix1gap.Agaz.2_a, mix1gap.Agaz.2_b))
}

Mix4 <- function(DF) {
  ZcwF07_a <- which(DF$mix4.ZcwF07_a != DF$mix4gap.ZcwF07_a | is.na(DF$mix4.ZcwF07_a) == T)
  ZcwF07_b <- which(DF$mix4.ZcwF07_b != DF$mix4gap.ZcwF07_b | is.na(DF$mix4.ZcwF07_b) == T)
  ZcwD02_a <- which(DF$mix4.ZcwD02_a != DF$mix4gap.ZcwD02_a | is.na(DF$mix4.ZcwD02_a) == T)
  ZcwD02_b <- which(DF$mix4.ZcwD02_b != DF$mix4gap.ZcwD02_b | is.na(DF$mix4.ZcwD02_b) == T)
  ZcwCgDh1.8_a <- which(DF$mix4.ZcwCgDh1.8_a != DF$mix4gap.ZcwCgDh1.8_a | is.na(DF$mix4.ZcwCgDh1.8_a) == T)
  ZcwCgDh1.8_b <- which(DF$mix4.ZcwCgDh1.8_b != DF$mix4gap.ZcwCgDh1.8_b | is.na(DF$mix4.ZcwCgDh1.8_b) == T)
  Aa4_a <- which(DF$mix4.Aa4_a != DF$mix4gap.Aa4_a | is.na(DF$mix4.Aa4_a) == T)
  Aa4_b <- which(DF$mix4.Aa4_b != DF$mix4gap.Aa4_b | is.na(DF$mix4.Aa4_b) == T)
  ZcCgDh5.8_a <- which(DF$mix4.ZcCgDh5.8_a != DF$mix4gap.ZcCgDh5.8_a | is.na(DF$mix4.ZcCgDh5.8_a) == T)
  ZcCgDh5.8_b <- which(DF$mix4.ZcCgDh5.8_b != DF$mix4gap.ZcCgDh5.8_b | is.na(DF$mix4.ZcCgDh5.8_b) == T)
  Agaz3_a <- which(DF$mix4.Agaz3_a != DF$mix4gap.Agaz3_a | is.na(DF$mix4.Agaz3_a) == T)
  Agaz3_b <- which(DF$mix4.Agaz3_b != DF$mix4gap.Agaz3_b | is.na(DF$mix4.Agaz3_b) == T)

  DF$mix4.ZcwF07_a[ZcwF07_a] <- DF$mix4gap.ZcwF07_a[ZcwF07_a]
  DF$mix4.ZcwF07_b[ZcwF07_b] <- DF$mix4gap.ZcwF07_b[ZcwF07_b]
  DF$mix4.ZcwD02_a[ZcwD02_a] <- DF$mix4gap.ZcwD02_a[ZcwD02_a]
  DF$mix4.ZcwD02_b[ZcwD02_b] <- DF$mix4gap.ZcwD02_b[ZcwD02_b]
  DF$mix4.ZcwCgDh1.8_a[ZcwCgDh1.8_a] <- DF$mix4gap.ZcwCgDh1.8_a[ZcwCgDh1.8_a]
  DF$mix4.ZcwCgDh1.8_b[ZcwCgDh1.8_b] <- DF$mix4gap.ZcwCgDh1.8_b[ZcwCgDh1.8_b]
  DF$mix4.Aa4_a[Aa4_a] <- DF$mix4gap.Aa4_a[Aa4_a]
  DF$mix4.Aa4_b[Aa4_b] <- DF$mix4gap.Aa4_b[Aa4_b]
  DF$mix4.ZcCgDh5.8_a[ZcCgDh5.8_a] <- DF$mix4gap.ZcCgDh5.8_a[ZcCgDh5.8_a]
  DF$mix4.ZcCgDh5.8_b[ZcCgDh5.8_b] <- DF$mix4gap.ZcCgDh5.8_b[ZcCgDh5.8_b]
  DF$mix4.Agaz3_a[Agaz3_a] <- DF$mix4gap.Agaz3_a[Agaz3_a]
  DF$mix4.Agaz3_b[Agaz3_b] <- DF$mix4gap.Agaz3_b[Agaz3_b]

  DF <- subset(DF, select = -c(mix4gap.ZcwF07_a, mix4gap.ZcwF07_b, mix4gap.ZcwD02_a, mix4gap.ZcwD02_b, mix4gap.ZcwCgDh1.8_a, mix4gap.ZcwCgDh1.8_b, mix4gap.Aa4_a, mix4gap.Aa4_b, mix4gap.ZcCgDh5.8_a, mix4gap.ZcCgDh5.8_b, mix4gap.Agaz3_a, mix4gap.Agaz3_b))
}

#bind the different mixes together
Data_df = do.call(cbind, Data_list)
#Separate the dataframe into Rack and treatment and remove this info from column names
R154_R1 <- Data_df %>% select(contains("Rack154")) %>% select(contains("_1")) %>%
  rename_with(~sub("Rack154_", "", .), everything()) %>%
  rename_with(~sub("_1", "", .), everything()) %>% ZcwCO1_loci() %>% Mangs_loci() %>% write_csv(., file.path(working_dir, "R154_R1.csv"))
R154_R2 <- Data_df %>% select(contains("Rack154")) %>% select(contains("_2")) %>%
  rename_with(~sub("Rack154_", "", .), everything()) %>%
  rename_with(~sub("_2", "", .), everything()) %>% ZcwCO1_loci() %>% write_csv(., file.path(working_dir, "R154_R2.csv"))
R154_R3 <- Data_df %>% select(contains("Rack154")) %>% select(contains("_3")) %>%
  rename_with(~sub("Rack154_", "", .), everything()) %>%
  rename_with(~sub("_3", "", .), everything()) %>% ZcwCO1_loci() %>% Mang44_loci() %>% OrrFCB2_loci() %>% Mix1() %>% Mix4() %>% write_csv(., file.path(working_dir, "R154_R3.csv"))
R154_R4 <- Data_df %>% select(contains("Rack154")) %>% select(contains("_4")) %>%
  rename_with(~sub("Rack154_", "", .), everything()) %>%
  rename_with(~sub("_4", "", .), everything()) %>% ZcwCO1_loci() %>% Mix1() %>% write_csv(., file.path(working_dir, "R154_R4.csv"))
R155_R1 <- Data_df %>% select(contains("Rack155")) %>% select(contains("_1")) %>%
  rename_with(~sub("Rack155_", "", .), everything()) %>%
  rename_with(~sub("_1", "", .), everything()) %>% ZcwCO1_loci() %>% Mangs_loci() %>% write_csv(., file.path(working_dir, "R155_R1.csv"))
R155_R2 <- Data_df %>% select(contains("Rack155")) %>% select(contains("_2")) %>%
  rename_with(~sub("Rack155_", "", .), everything()) %>%
  rename_with(~sub("_2", "", .), everything()) %>% ZcwCO1_loci() %>% Mang44_loci()
R155_R2$mix3.ZcwDh4.7_b[1] <- 262
write_csv(R155_R2, file.path(working_dir, "R155_R2.csv"))
R155_R3 <- Data_df %>% select(contains("Rack155")) %>% select(contains("_3")) %>%
  rename_with(~sub("Rack155_", "", .), everything()) %>%
  rename_with(~sub("_3", "", .), everything()) %>% ZcwCO1_loci() %>% OrrFCB2_loci() %>% PvcEMangs() %>% write_csv(., file.path(working_dir, "R155_R3.csv"))
R155_R4 <- Data_df %>% select(contains("Rack155")) %>% select(contains("_4")) %>%
  rename_with(~sub("Rack155_", "", .), everything()) %>%
  rename_with(~sub("_4", "", .), everything()) %>% ZcwCO1_loci() %>% write_csv(., file.path(working_dir, "R155_R4.csv"))
R156_R1 <- Data_df %>% select(contains("Rack156")) %>% select(contains("_1")) %>%
  rename_with(~sub("Rack156_", "", .), everything()) %>%
  rename_with(~sub("_1", "", .), everything()) %>% ZcwCO1_loci() %>% Mangs_loci() %>% write_csv(., file.path(working_dir, "R156_R1.csv"))
R156_R2 <- Data_df %>% select(contains("Rack156")) %>% select(contains("_2")) %>%
  rename_with(~sub("Rack156_", "", .), everything()) %>%
  rename_with(~sub("_2", "", .), everything()) %>% ZcwCO1_loci() %>% Mix4() %>% write_csv(., file.path(working_dir, "R156_R2.csv"))
R156_R3 <- Data_df %>% select(contains("Rack156")) %>% select(contains("_3")) %>%
  rename_with(~sub("Rack156_", "", .), everything()) %>%
  rename_with(~sub("_3", "", .), everything()) %>% ZcwCO1_loci() %>% PvcEMangs4436() %>% write_csv(., file.path(working_dir, "R156_R3.csv"))
R156_R4 <- Data_df %>% select(contains("Rack156")) %>% select(contains("_4")) %>%
  rename_with(~sub("Rack156_", "", .), everything()) %>%
  rename_with(~sub("_4", "", .), everything()) %>% ZcwCO1_loci() %>% write_csv(., file.path(working_dir, "R156_R4.csv"))

rm(Data_df, Data_list, x, Data_files, i, Mix1, Mix1_locate, remove_row, Mang44_loci, Mangs_loci, Mix4, Mix1, OrrFCB2_loci, PvcEMangs, PvcEMangs4436, ZcwCO1_loci)
```
